platform :ios, '14.0'
use_modular_headers!

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

# No pre_install hacks required with static linkage frameworks

target 'Runner' do
  use_frameworks! :linkage => :static

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      # Enforce modular header settings and allow non-modular includes where necessary
      config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
      config.build_settings['FORBID_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'NO'
      config.build_settings['DEFINES_MODULE'] = 'YES'
      
      # Additional compiler flags to suppress the non-modular header error
      config.build_settings['OTHER_CFLAGS'] ||= '$(inherited)'
      config.build_settings['OTHER_CFLAGS'] += ' -Wno-non-modular-include-in-framework-module -Wno-error=non-modular-include-in-framework-module'
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= '$(inherited)'
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] += ' CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES=1'

      config.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
      
      # Force IPHONEOS_DEPLOYMENT_TARGET to 14.0
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'

      base_config = config.base_configuration_reference
      if base_config
        xcconfig_path = base_config.real_path
        if File.exist?(xcconfig_path)
          xcconfig = File.read(xcconfig_path)
          if xcconfig.include?("DT_TOOLCHAIN_DIR")
            xcconfig.gsub!("DT_TOOLCHAIN_DIR", "TOOLCHAIN_DIR")
            File.open(xcconfig_path, "w") { |file| file << xcconfig }
          end
        end
      end
    end
  end
end
